<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_q</name>
   <tag></tag>
   <elementGuidId>d9773854-954f-4f82-86cc-fc28adfda260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sb_form_q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sb_form_q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5162fd4a-99b9-48fd-9392-56ab2a273a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sb_form_q</value>
      <webElementGuid>4c580466-226e-4021-b300-58839310164d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sb_form_q</value>
      <webElementGuid>397802dc-9175-418b-adab-b4ba24b925f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>c69e3ec1-3c8f-4f97-9f98-e9e248d81352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4c99a5d3-7259-4bf5-84c1-79ed62118c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>100fc333-ef69-44ed-93fb-dd9ccf46c60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ebfb3e8-7974-4491-902a-a6b8e85c94ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter your search term</value>
      <webElementGuid>a5b63316-2737-42ec-8cb2-39478854530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sw_as</value>
      <webElementGuid>0bdcda81-eb28-42e3-b1d6-ab163c900922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>2b77ae24-7997-4d35-8baf-a0df6656ab7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>sw_as</value>
      <webElementGuid>3fb74830-95ab-4203-b50d-a28e8291b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bm</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9bd448c4-ef74-497d-9493-8177aa4f9f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sb_form_q&quot;)</value>
      <webElementGuid>d873b19e-22e7-4ed0-87c9-b1ee8b1ca820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sb_form_q']</value>
      <webElementGuid>85479c09-6ef9-4e03-bd50-69049960287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sb_form']/input</value>
      <webElementGuid>c3a715f8-7f06-47c5-9a74-20ec37f5628c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>752b172c-a6e6-4649-a5ea-353e1f583aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sb_form_q' and @name = 'q' and @type = 'search']</value>
      <webElementGuid>6b103ae4-c35e-45cd-843c-3a5095778aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
